services:
  fastapi:
    container_name: ovpn-st_fastapi
    build: .
    ports:
      - 9004:9004
    volumes:
      - ./fastapi:/src
      - ./openvpn-status.log:/src/openvpn-status.log
    working_dir: /src
    command: uvicorn main:app --reload --host 0.0.0.0 --port 9004
    environment:
      - TZ=Asia/Tokyo